apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: clickhouse
spec:
  entryPoints:
    - clickhouse
  routes:
    - match: HostSNI(`*`)
      services:
        - name: clickhouse
          port: 9000