apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-replica-data-clickhouse-replica-0
spec:
  storageClassName: clickhouse-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      pv: local-replica
