apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv-volume
  labels:
    type: local
spec:
  storageClassName: clickhouse-sc
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host/wwwdata/clickhouse-k8s