apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv-volume-replica
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host/wwwdata/clickhouse-replica-k8s