apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-etcd-0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: etcd-pv-volume
