apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rabbitmq
spec:
  entryPoints:
    - rabbitmq
    - rabbitmqmanager
  routes:
    - match: HostSNI(`*`)
      services:
        - name: rabbitmq
          port: 5672
        - name: rabbitmq
          port: 15672
