apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmq-0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: rabbitmq-pv-volume
