apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host/wwwdata/rabbitmq-k8s
