apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  storageClassName: mongodb-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi