apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pv-claim
spec:
  storageClassName: cassandra-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi