apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nsq
spec:
  entryPoints:
    - nsqd
    - nsqlookupd
  routes:
    - match: HostSNI(`*`)
      services:
        - name: nsq-nsqd
          port: 4150
        - name: nsq-nsqlookupd
          port: 4160
