apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nsq-nsqd-0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: nsq-pv-volume
