apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-replicas-0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: redis-pv-volume-replica
